const EDIT_HERO = "UPDATE_HERO";
const NEW_HERO = "NEW_HERO";
const DELETE_HERO = "DELETE_HERO";
const HERO_SELECTED = "HERO_SELECTED";
const GIT_SEARCH = "GIT_SEARCH";
const ASIGN_GIT = "ASIGN_GIT";
const ASSIGN_USER = "ASSIGN_USER";
const USER_SEARCH = "USER_SEARCH";
export {
    HERO_SELECTED,
    NEW_HERO,
    EDIT_HERO,
    DELETE_HERO,
    GIT_SEARCH,
    ASIGN_GIT,
    ASSIGN_USER,
    USER_SEARCH
};